controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
weather:
    path: /
    controller: App\Controller\WeatherController::index
forecast:
    path: /forecast
    controller: App\Controller\WeatherController::forecast